---
title: "R Class_20230809"
author: "Anita Makori"
date: "2023-08-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load packages
library(tidyverse)
library(janitor)
library(sf) #install.packages("sf")
library(ggplot2)
library(readxl) #install.packages("readxl")
```


```{r county_data, include=FALSE}
# reading the datasets

county_data <- st_read("County.shp") %>%
  rename(county=Name)

density_data <- read_excel("Density.xlsx")%>%
  clean_names()

# get county names in density data
densitycounties <- unique(density_data$county)
# get county names in shapefile data
shapecounties <- unique(county_data$county)
# get county names that are in density data but not in shapefile data
densitycounties[which(!densitycounties%in%shapecounties)]

# recode misspelt county names in density data
density_data <- density_data %>%
  mutate(county=recode(county, "Keiyo-Marakwet"="Elgeyo Marakwet", "Murang'A"="Muranga"))
```

```{r plot shapefile data}
ggplot (county_data) +
  geom_sf(aes(geometry=geometry))
```

```{r merge data}
merged_density_data <- county_data %>%
  left_join(density_data, by="county")
```

```{r plot density map}
ggplot(merged_density_data) +
  geom_sf(aes(geometry=geometry, fill=density_of_physician_hwf_per_10_000_population)) +
  theme_void() +
  labs(x="", y="", fill="Physician Density", title = "Map showing physician density per county") +
  scale_fill_gradient(low = "white", high = "#006d2c")
```

